export { default as Contact } from './Contact.vue'
export { default as Technologies } from './Technologies.vue'
export { default as Languages } from './Languages.vue'
export { default as Sidebar } from './Sidebar.vue'
export { default as Experience } from './Experience.vue'
export { default as Education } from './Education.vue'